## Vorbereitung

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("MdB_Indexed.csv")
df = df.set_index("WP-JAHRE")
df.head()

NUMIND  ANFANG  ALTER  GESCHLECHT PARTEI_KURZ  \
WP-JAHRE                                                      
1949-1953;01       0    1949     73           1       Union   
1949-1953;01       1    1949     45           1      Andere   
1949-1953;01       2    1949     70           1      Andere   
1949-1953;01       3    1949     59           1       Union   
1949-1953;01       4    1949     48           0         SPD   

                                          BERUF  AUSLAND  MANDATSART  WP1  \
WP-JAHRE                                                                    
1949-1953;01                Bundeskanzler a. D.        0         1.0    1   
1949-1953;01  Bergmann, Gewerkschaftsfunktionär        0         0.0    1   
1949-1953;01                      Kapitän a. D.        0         0.0    1   
1949-1953;01                    Geschäftsführer        0         1.0    1   
1949-1953;01                       Buchhalterin        0         0.0    1   

              WP2  ...   WP10  WP11  WP12  WP13  WP14  WP15  WP16  WP17  WP18  \
WP-JAHRE           ...                                                          
1949-1953;01    1  ...      0     0     0     0     0     0     0     0     0   
1949-1953;01    0  ...      0     0     0     0     0     0     0     0     0   
1949-1953;01    0  ...      0     0     0     0     0     0     0     0     0   
1949-1953;01    1  ...      0     0     0     0     0     0     0     0     0   
1949-1953;01    1  ...      0     0     0     0     0     0     0     0     0   

              WP19  
WP-JAHRE            
1949-1953;01     0  
1949-1953;01     0  
1949-1953;01     0  
1949-1953;01     0  
1949-1953;01     0  

[5 rows x 27 columns]

In [3]:
df[df["MANDATSART"].isnull()]

NUMIND  ANFANG  ALTER  GESCHLECHT PARTEI_KURZ  \
WP-JAHRE                                                      
1998–2002;14    8023    1998     43           1       Union   

                                           BERUF  AUSLAND  MANDATSART  WP1  \
WP-JAHRE                                                                     
1998–2002;14  Dipl.-Ingenieur für Schiffstechnik        0         NaN    0   

              WP2  ...   WP10  WP11  WP12  WP13  WP14  WP15  WP16  WP17  WP18  \
WP-JAHRE           ...                                                          
1998–2002;14    0  ...      0     0     0     1     1     1     0     0     0   

              WP19  
WP-JAHRE            
1998–2002;14     0  

[1 rows x 27 columns]

In [4]:
df["MANDATSART"].fillna(0, inplace=True)


In [6]:
df[df["MANDATSART"].isnull()]

Empty DataFrame
Columns: [NUMIND, ANFANG, ALTER, GESCHLECHT, PARTEI_KURZ, BERUF, AUSLAND, MANDATSART, WP1, WP2, WP3, WP4, WP5, WP6, WP7, WP8, WP9, WP10, WP11, WP12, WP13, WP14, WP15, WP16, WP17, WP18, WP19]
Index: []

[0 rows x 27 columns]

In [7]:
df = df.drop(["NUMIND", "BERUF"], axis = 1)

df.head()

ANFANG  ALTER  GESCHLECHT PARTEI_KURZ  AUSLAND  MANDATSART  WP1  \
WP-JAHRE                                                                        
1949-1953;01    1949     73           1       Union        0         1.0    1   
1949-1953;01    1949     45           1      Andere        0         0.0    1   
1949-1953;01    1949     70           1      Andere        0         0.0    1   
1949-1953;01    1949     59           1       Union        0         1.0    1   
1949-1953;01    1949     48           0         SPD        0         0.0    1   

              WP2  WP3  WP4  ...   WP10  WP11  WP12  WP13  WP14  WP15  WP16  \
WP-JAHRE                     ...                                              
1949-1953;01    1    1    1  ...      0     0     0     0     0     0     0   
1949-1953;01    0    0    0  ...      0     0     0     0     0     0     0   
1949-1953;01    0    0    0  ...      0     0     0     0     0     0     0   
1949-1953;01    1    0    0  ...      0     0     0     0     0     0     0   
1949-1953;01    1    1    1  ...      0     0     0     0     0     0     0   

              WP17  WP18  WP19  
WP-JAHRE                        
1949-1953;01     0     0     0  
1949-1953;01     0     0     0  
1949-1953;01     0     0     0  
1949-1953;01     0     0     0  
1949-1953;01     0     0     0  

[5 rows x 25 columns]

In [8]:
uniq = list(df.index.unique())
print(uniq)

#Einzelne DFs
df_WP01 = df.loc[uniq[0]]
df_WP02 = df.loc[uniq[1]]
df_WP03 = df.loc[uniq[2]]
df_WP04 = df.loc[uniq[3]]
df_WP05 = df.loc[uniq[4]]
df_WP06 = df.loc[uniq[5]]
df_WP07 = df.loc[uniq[6]]
df_WP08 = df.loc[uniq[7]]
df_WP09 = df.loc[uniq[8]]
df_WP10 = df.loc[uniq[9]]
df_WP11 = df.loc[uniq[10]]
df_WP12 = df.loc[uniq[11]]
df_WP13 = df.loc[uniq[12]]
df_WP14 = df.loc[uniq[13]]
df_WP15 = df.loc[uniq[14]]
df_WP16 = df.loc[uniq[15]]
df_WP17 = df.loc[uniq[16]]
df_WP18 = df.loc[uniq[17]]
df_WP19 = df.loc[uniq[18]]


df_wp_list = [df_WP01, df_WP02, df_WP03, df_WP04, df_WP05, df_WP06, df_WP07, df_WP08, df_WP09, df_WP10, df_WP11, df_WP12, df_WP13,
df_WP14,df_WP15,df_WP16,df_WP17,df_WP18, df_WP19]


NumberMdBs= []
for e in df_wp_list:
    NumberMdBs.append(len(e["WP1"]))

print(NumberMdBs)


#Test
df_WP05.head()

['1949-1953;01', '1953–1957;02', '1957–1961;03', '1961–1965;04', '1965–1969;05', '1969–1972;06', '1972–1976;07', '1976-1980;08', '1980–1983;09', '1983–1987;10', '1987–1990;11', '1990–1994;12', '1994–1998;13', '1998–2002;14', '2002–2005;15', '2005–2009;16', '2009–2013;17', '2013–2017;18', '2017-;19']
[474, 558, 562, 580, 559, 556, 549, 553, 549, 576, 702, 699, 693, 699, 628, 642, 652, 658, 711]


ANFANG  ALTER  GESCHLECHT PARTEI_KURZ  AUSLAND  MANDATSART  WP1  \
WP-JAHRE                                                                        
1965–1969;05    1965     35           1       Union        0         1.0    0   
1965–1969;05    1965     56           1         FDP        0         0.0    0   
1965–1969;05    1965     46           1         SPD        0         0.0    0   
1965–1969;05    1965     89           1       Union        0         1.0    1   
1965–1969;05    1965     45           1       Union        0         1.0    0   

              WP2  WP3  WP4  ...   WP10  WP11  WP12  WP13  WP14  WP15  WP16  \
WP-JAHRE                     ...                                              
1965–1969;05    0    0    0  ...      1     1     0     0     0     0     0   
1965–1969;05    0    1    1  ...      0     0     0     0     0     0     0   
1965–1969;05    0    0    0  ...      0     0     0     0     0     0     0   
1965–1969;05    1    1    1  ...      0     0     0     0     0     0     0   
1965–1969;05    0    0    1  ...      0     0     0     0     0     0     0   

              WP17  WP18  WP19  
WP-JAHRE                        
1965–1969;05     0     0     0  
1965–1969;05     0     0     0  
1965–1969;05     0     0     0  
1965–1969;05     0     0     0  
1965–1969;05     0     0     0  

[5 rows x 25 columns]

In [9]:
#Transformieren der Spalte für Parteikürzel in einzelne, binäre Spalten

def binary_transformer(dafr):
    uni_lst = list(dafr["PARTEI_KURZ"].unique())
    for e in uni_lst:
        dafr[e]= dafr["PARTEI_KURZ"] == e
        dafr[e].replace([True, False], [1,0], inplace = True)
        

for e in df_wp_list:
    binary_transformer(e)
    
df_WP10.head()

C:\Users\Laszlo Kuehl\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Laszlo Kuehl\Anaconda3\lib\site-packages\pandas\core\generic.py:5890: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


ANFANG  ALTER  GESCHLECHT PARTEI_KURZ  AUSLAND  MANDATSART  WP1  \
WP-JAHRE                                                                        
1983–1987;10    1983     53           1       Union        0         1.0    0   
1983–1987;10    1983     59           1         SPD        0         0.0    0   
1983–1987;10    1983     55           1       Union        0         1.0    0   
1983–1987;10    1983     49           1         SPD        0         0.0    0   
1983–1987;10    1983     44           1         SPD        0         0.0    0   

              WP2  WP3  WP4 ...   WP14  WP15  WP16  WP17  WP18  WP19  Union  \
WP-JAHRE                    ...                                               
1983–1987;10    0    0    0 ...      0     0     0     0     0     0      1   
1983–1987;10    0    0    0 ...      0     0     0     0     0     0      0   
1983–1987;10    0    0    1 ...      0     0     0     0     0     0      1   
1983–1987;10    0    0    0 ...      0     0     0     0     0     0      0   
1983–1987;10    0    0    0 ...      0     0     0     0     0     0      0   

              SPD  Bündnis 90/Die Grünen  FDP  
WP-JAHRE                                       
1983–1987;10    0                      0    0  
1983–1987;10    1                      0    0  
1983–1987;10    0                      0    0  
1983–1987;10    1                      0    0  
1983–1987;10    1                      0    0  

[5 rows x 29 columns]

In [10]:
#Dropping redundant columns for automated modelling

wp_list = np.array(["WP1","WP2","WP3","WP4","WP5","WP6","WP7","WP8","WP9","WP10","WP11","WP12","WP13","WP14","WP15","WP16","WP17","WP18","WP19"])	

def del_redun(dafr):
    num = int(dafr.index[0][-2:])
    ind = np.array(range(0,19))
    sel = list(ind[ind>num])
    sel.append(ind[num-1])
    drop_cols = list(wp_list[sel])
    return drop_cols

for d in list(range(0,19)):
    drop = list(del_redun(df_wp_list[d]))
    df_wp_list[d] = df_wp_list[d].drop(drop, axis = 1)

for e in list(range(0,19)):
    drop = ["ANFANG", "PARTEI_KURZ"]
    df_wp_list[e] = df_wp_list[e].drop(drop, axis = 1)
    

df_wp_list[3].head()

ALTER  GESCHLECHT  AUSLAND  MANDATSART  WP1  WP2  WP3  WP5  FDP  \
WP-JAHRE                                                                        
1961–1965;04     52           1        0         0.0    0    0    1    1    1   
1961–1965;04     48           0        1         0.0    0    1    1    0    0   
1961–1965;04     85           1        0         1.0    1    1    1    1    0   
1961–1965;04     41           1        0         1.0    0    0    0    1    0   
1961–1965;04     37           1        0         1.0    0    0    1    1    0   

              Union  SPD  Andere  
WP-JAHRE                          
1961–1965;04      0    0       0  
1961–1965;04      1    0       0  
1961–1965;04      1    0       0  
1961–1965;04      1    0       0  
1961–1965;04      1    0       0

In [18]:
#Z-Transformation des Alters
for d in list(range(0,19)):
     df_wp_list[d]["ALTER"] = (df_wp_list[d]["ALTER"] -  df_wp_list[d]["ALTER"].mean())/df_wp_list[d]["ALTER"].std()

In [19]:
#Resetting Index
for e in df_wp_list:
     e.index = range(len(list(e.index)))

df_wp_list[6].head()

ALTER  GESCHLECHT  AUSLAND  MANDATSART  WP1  WP2  WP3  WP4  WP5  WP6  \
0 -0.485003           1        0         1.0    0    0    0    0    1    1   
1  1.848721           1        0         0.0    0    0    1    1    1    1   
2  0.737424           1        0         1.0    0    0    0    0    1    1   
3  0.404034           1        0         1.0    0    0    0    0    0    0   
4  0.181775           1        0         1.0    0    0    0    0    0    1   

   WP8  Union  FDP  SPD  
0    1      1    0    0  
1    0      0    1    0  
2    1      0    0    1  
3    1      0    0    1  
4    1      0    0    1

## Prediction 

In [29]:

from sklearn.cross_validation import cross_val_score

from sklearn import metrics
from matplotlib import pyplot as plt

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression


#from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF



In [26]:
for i in list(range(0,18)):
    df = df_wp_list[i]
    wpnum = "WP" + str(int(i+2))
    X, y = df.loc[:, df.columns != wpnum], df[wpnum]
    gnb = GaussianNB()
    scores = cross_val_score(gnb, X,y, cv = 5, scoring ="accuracy")
    print(scores)

[0.73684211 0.71578947 0.69473684 0.75789474 0.69148936]
[0.72321429 0.74107143 0.6875     0.69642857 0.72727273]
[0.71681416 0.73451327 0.73214286 0.73214286 0.72321429]
[0.33333333 0.32758621 0.32758621 0.32758621 0.72173913]
[0.3539823  0.3539823  0.35135135 0.35135135 0.58558559]
[0.72321429 0.61607143 0.71171171 0.66666667 0.7       ]
[0.73873874 0.67272727 0.78181818 0.71559633 0.69724771]
[0.71428571 0.2972973  0.79090909 0.72727273 0.70909091]
[0.72072072 0.69090909 0.76363636 0.81651376 0.2293578 ]
[0.76724138 0.7826087  0.77391304 0.7826087  0.73913043]
[0.67375887 0.68085106 0.68571429 0.69285714 0.73571429]
[0.35460993 0.62142857 0.67142857 0.65467626 0.66906475]
[0.73381295 0.76258993 0.71942446 0.26811594 0.7173913 ]
[0.42857143 0.52142857 0.65714286 0.7        0.74820144]
[0.26984127 0.26190476 0.28571429 0.264      0.704     ]
[0.3875969  0.71317829 0.6796875  0.6640625  0.640625  ]
[0.52671756 0.71755725 0.76153846 0.87692308 0.81538462]
[0.5112782  0.63636364 0.641221

In [25]:
for i in list(range(0,18)):
    df = df_wp_list[i]
    wpnum = "WP" + str(int(i+2))
    X, y = df.loc[:, df.columns != wpnum], df[wpnum]
    log = LogisticRegression()
    scores = cross_val_score(log, X,y, cv = 5, scoring ="accuracy")
    print(scores)

[0.74736842 0.69473684 0.68421053 0.77894737 0.70212766]
[0.75       0.73214286 0.70535714 0.72321429 0.68181818]
[0.74336283 0.72566372 0.75892857 0.6875     0.72321429]
[0.70940171 0.75       0.77586207 0.80172414 0.69565217]
[0.75221239 0.76106195 0.77477477 0.77477477 0.72972973]
[0.74107143 0.70535714 0.72972973 0.73873874 0.77272727]
[0.76576577 0.74545455 0.76363636 0.73394495 0.74311927]
[0.72321429 0.78378378 0.78181818 0.7        0.77272727]
[0.78378378 0.75454545 0.79090909 0.79816514 0.78899083]
[0.77586207 0.7826087  0.77391304 0.77391304 0.8       ]
[0.71631206 0.70212766 0.64285714 0.67857143 0.74285714]
[0.65957447 0.69285714 0.69285714 0.69784173 0.76258993]
[0.74100719 0.76978417 0.71942446 0.80434783 0.74637681]
[0.57857143 0.67857143 0.51428571 0.69285714 0.73381295]
[0.61111111 0.46031746 0.5952381  0.72       0.736     ]
[0.48837209 0.58914729 0.671875   0.6953125  0.6875    ]
[0.51145038 0.71755725 0.78461538 0.86153846 0.80769231]
[0.5037594  0.56060606 0.648854

In [30]:
for i in list(range(0,18)):
    df = df_wp_list[i]
    wpnum = "WP" + str(int(i+2))
    X, y = df.loc[:, df.columns != wpnum], df[wpnum]
    model = GaussianProcessClassifier(random_state=0)
    scores = cross_val_score(model, X,y, cv = 5, scoring ="accuracy")
    print(scores)

[0.75789474 0.70526316 0.73684211 0.71578947 0.72340426]
[0.69642857 0.73214286 0.69642857 0.71428571 0.71818182]
[0.75221239 0.72566372 0.76785714 0.6875     0.72321429]
[0.7008547  0.73275862 0.73275862 0.76724138 0.73043478]
[0.76106195 0.74336283 0.76576577 0.72972973 0.72072072]
[0.77678571 0.73214286 0.73873874 0.74774775 0.82727273]
[0.78378378 0.72727273 0.75454545 0.72477064 0.76146789]
[0.72321429 0.8018018  0.79090909 0.70909091 0.75454545]
[0.77477477 0.78181818 0.77272727 0.81651376 0.79816514]
[0.75       0.79130435 0.80869565 0.8        0.7826087 ]
[0.73758865 0.72340426 0.65714286 0.71428571 0.74285714]
[0.67375887 0.67142857 0.73571429 0.73381295 0.75539568]
[0.76258993 0.81294964 0.74820144 0.80434783 0.76086957]
[0.65       0.69285714 0.65       0.70714286 0.72661871]
[0.65873016 0.57936508 0.71428571 0.728      0.736     ]
[0.62790698 0.60465116 0.6328125  0.671875   0.6796875 ]
[0.55725191 0.7480916  0.78461538 0.86153846 0.80769231]
[0.63157895 0.62878788 0.664122

In [32]:
#for i in list(range(0,18)):
    #df = df_wp_list[i]
    #wpnum = "WP" + str(int(i+2))
    #X, y = df.loc[:, df.columns != wpnum], df[wpnum]
    #model = GaussianProcessClassifier(1.0 * RBF(1.0), random_state=0)
    #scores = cross_val_score(model, X,y, cv = 5, scoring ="accuracy")
    #print(scores)

[0.72631579 0.71578947 0.71578947 0.71578947 0.71276596]
[0.71428571 0.73214286 0.71428571 0.70535714 0.70909091]
[0.73451327 0.73451327 0.74107143 0.69642857 0.71428571]
[0.7008547  0.75       0.75862069 0.80172414 0.72173913]
[0.7699115  0.74336283 0.77477477 0.75675676 0.71171171]
[0.77678571 0.75       0.73873874 0.72972973 0.79090909]
[0.78378378 0.73636364 0.77272727 0.73394495 0.73394495]
[0.74107143 0.8018018  0.77272727 0.71818182 0.75454545]
[0.77477477 0.79090909 0.77272727 0.80733945 0.78899083]
[0.78448276 0.80869565 0.80869565 0.79130435 0.8       ]
[0.74468085 0.73049645 0.67142857 0.72857143 0.73571429]
[0.68794326 0.68571429 0.7        0.69784173 0.74820144]
[0.79136691 0.82014388 0.74100719 0.80434783 0.76811594]
[0.66428571 0.75       0.63571429 0.70714286 0.76258993]
[0.66666667 0.50793651 0.67460317 0.736      0.736     ]
[0.58914729 0.60465116 0.6328125  0.6953125  0.671875  ]
[0.48091603 0.72519084 0.77692308 0.86923077 0.80769231]
[0.56390977 0.52272727 0.664122